### ISSUE TITLE
Fonction phenix ne marche plus

### ISSUE THREAD

**Issue by adharna** [zahiid/KingTouch#10]
[INACTIVITY] Soft debug on Adharna11 .
[Sync]Processing ...
[Sync]Ready to process !
[Sync]On est un fantome ! (84673546)
[Sync]On a trouver un phoenix sur la cell 258
Mouvement vers l'interactive sur la cellule : 258=258
Exectution du trajet vers l'interactive .
pas de mouvement à faire wesh x)
Utlisiation de l'interactive (id : 479466,skill : 152192)
[INACTIVITY] Soft debug on Adharna11 .
[Sync]Processing ...
[Sync]Ready to process !
[Sync]On est un fantome ! (84673546)
[Sync]On a trouver un phoenix sur la cell 258
Mouvement vers l'interactive sur la cellule : 258=258
Exectution du trajet vers l'interactive .
pas de mouvement à faire wesh x)
Utlisiation de l'interactive (id : 479466,skill : 152192)
[INACTIVITY] Soft debug on Adharna11 .
[Sync]Processing ...
[Sync]Ready to process !
[Sync]On est un fantome ! (84673546)
[Sync]On a trouver un phoenix sur la cell 258
Mouvement vers l'interactive sur la cellule : 258=258
Exectution du trajet vers l'interactive .
pas de mouvement à faire wesh x)
Utlisiation de l'interactive (id : 479466,skill : 152192)
[INACTIVITY] Soft debug on Adharna11 .
[Sync]Processing ...
[Sync]Ready to process !
[Sync]On est un fantome ! (84673546)
[Sync]On a trouver un phoenix sur la cell 258
Mouvement vers l'interactive sur la cellule : 258=258
Exectution du trajet vers l'interactive .
pas de mouvement à faire wesh x)
Utlisiation de l'interactive (id : 479466,skill : 152192)

'Message sent :'
{ call: 'sendMessage',
  data: 
   { type: 'InteractiveUseRequestMessage',
     data: { elemId: 479466, skillInstanceUid: 152192 } } }
'Message reveived :'
{ _messageType: 'BasicAckMessage',
  seq: 17,
  lastPacketId: 5001,
  _isInitialized: true }
'Message reveived :'
{ _messageType: 'BasicNoOperationMessage' }
'Message reveived :'
{ _messageType: 'GameMapMovementMessage',
  keyMovements: [ 188, 130 ],
  actorId: -3,
  _isInitialized: true }

**Comment by asyade** [comment]
Normale le bot est plus a jours :D, si non je pense pas qu'il y est de grosses modif a ce niveaux regarde un peut le code il y a un array qui contiens { MAPID DU PHOENIX, ID DU PHOENIX } il faut peutétre ajouter le tiens et pour ce qui est du chemin jusque au phoenix il faut le gerer dans les trajet pas de world pathfinding
