### ISSUE TITLE
Lancement d'un trajet

### ISSUE THREAD

**Issue by Spyrow** [zahiid/KingTouch#6]
Je poste ma demande de Cadernis ici au cas ou vous passez plutôt par ici !

Franchement la fois dernière j'étais perdu puis j'ai bien relu le sujet principale pour comprendre le fonctionnement et j'ai compris l'environnement autour du coup c'est passé crème !
Là pour le moment j'essaye les trajets car c'est la fonction indispensable ( normal) :vicieux:. Mais pour le moment j'ai un bug au niveau du code à l’exécution d'une action du trajet et vu que le JS c'est pas trop mon truc je comprends l'erreur mais je sais pas trop comment y remédier mais je tryhard !

( dans le trajet.js ligne 112 )
Code (Text):
if(this.currentTrajet.mouvement[coords]) map = this.currentTrajet.mouvement[coords];
L'erreur : Cannot read property '1,4' of undefined

J'ai fais des recherches sur cette erreur mais bon c'est sur des domaines différents donc j'ai rien trouvé de vraiment similaire à mon problème.( je continue à chercher )

**Comment by asyade** [comment]
Le systeme de trajet etais en refonte et c'es zaide qui s'en chargais ^^'
je pourais pas trop taider mais il semble que sa soie un pb de parsing
montre ton trajet

**Comment by Spyrow** [comment]
En effet je pense que tu as raison,  j'ai réussi a faire fonctionner le trajet mais uniquement avec la fonction mouvement. J'ai essayé avec le mot clé recolte et combat/fight mais ça fait toujours la même erreur que sur mon premier post : `mouvement :
  [0,-14] :
    direction :
      top
  [0,-15]:
    direction : bottom
    
`
Ce code fonctionne mais si je mets fight/combat/recolte à la place ça fait l'erreur comme plus haut.

**Comment by Spyrow** [comment]
Oui j'ai toujours le problème mais c'est surement moi qui fait pas ce qui faut mais je comprends pas trop le système de trajet, j'ai essayé pas mal de choses mais y'a que le mouvement qui fonctionne et pas le reste... surement ma syntaxe de trajet qui est mauvaise ?

**Comment by zahiid** [comment]
tu peux me montrer le trajet exact que tu testes la dessus stp ?

**Comment by Spyrow** [comment]
J'ai essayé ça: (si je mets mouvement à la place de combat ça fonctionne nikel et recolte ça bug aussi )
`combat :
  [-1,-16] :
    direction :
      top
  [0,-15]:
    direction : bottom
    `

**Comment by zahiid** [comment]
Je ne vois pas d'espaces pour marquer les noeuds (comme l'exige le YAML) et si ça te derange pas , tu peux me mettre ta version du bot (flemme de tout mettre a jour pour tester les trajets ^^)

**Comment by Spyrow** [comment]
Les nœuds sont bien là c'est juste que l'indentation n'a pas été prise en compte, on est 2 maintenant sur le projet on a trouvé plus ou moins le problème le code ne prend en compte que la fonction mouvement on arrive pas a utiliser deux fonctions différentes dans un trajet c'est le problème.

**Comment by zahiid** [comment]
https://pastebin.com/61EZBVNh

**Comment by Spyrow** [comment]
OK Je vais essayer merci

**Comment by zahiid** [comment]
à titre de curiosité , ton travail avec ton ami est privé ou vous comptez passer en open ? ^^

**Comment by Spyrow** [comment]
J'ai testé il était en -1,-14 il me marque action invalide right

**Comment by Spyrow** [comment]
Vu comment on rame pour le moment les gens ne ratent rien mais je ne sais pas du tout pour l'instant

**Comment by zahiid** [comment]
t'as pas la dernier version du bot du coup

**Comment by zahiid** [comment]
https://pastebin.com/LW9d4g9h , tiens vérifie si t'as cette version du fichier trajet.js , je crois qu'Asyade n'a pas mis la bonne version

**Comment by Spyrow** [comment]
Ah ouais rien à voir ça devrait mieux fonctionner maintenant lol merci je testerai ça dès que je peux ;)

**Comment by zahiid** [comment]
Faut que je mette ma version du bot sur gît , y'a pas mal de bugs que j'ai corrigé .

**Comment by Spyrow** [comment]
Ah ouais cool moi je test les combats du coup grâce au trajet mais il passe son tour en boucle j'ai config le pied du sacri comme il faut mais rien à faire :D je cherche du coup là.

**Comment by zahiid** [comment]
Ah oui , je me suis chargé de la refonte du systeme combats , si tu trouves des difficultés n’hésite pas ^^'

**Comment by Spyrow** [comment]
Est ce que je dois modifier quelque chose pour ce système ou c'est censé fonctionner ?

**Comment by zahiid** [comment]
T'as pas la bonne version du bot , je mettrais cette aprem ma version .

**Comment by finitha** [comment]
il est possible d'upload la nouvelle version du bot ?
