### ISSUE TITLE
Anti bot

### ISSUE THREAD

**Issue by iron-maiden74** [zahiid/KingTouch#7]
Salut, j'ai commencé à utiliser le bot (apres quelques modifications), et je viens d'etre ban 2 jours.
Donc question : est ce qu'il y a un anti ban ? si oui comment ca marche ?
J'ai eu plusieurs fois des messages "etes vous un bot" avec un captcha (uniquement sur bot combat), et j'etais obligé de me co sur mon tel pour débloquer le bot.
comment gérer ca ?
Merci

**Comment by asyade** [comment]
Le bot d'ate de 3-4 moins, aucune protection particuliere, il marchais bien ce n'est surment plus le cas (jamais vue cette protection c'est nouveau) si tu trouve je tinvinte a partager ta soluce sur le git que les autres en profite ;)

**Comment by Spyrow** [comment]
Il n'y a pas d'anti-bot c'est juste un modo comme sur DofusPC , par contre pour les captchas c'est assez contraignant mais comme tu l'a dis c'est uniquement sur les bots qui font pas mal de combat ( pour la récolte j'ai jamais eu de captcha ) il faut juste pouvoir gérer les captchas tu peux passer par une société externe qui les résous à ta place mais ça te coûtera des $

**Comment by zahiid** [comment]
T'es sur de ce que tu dis Spyrow ? ^^ 
Parce que , personnellement , quand j'utilisais le bot , j'ai récolté pas mal de bans instantanés ce qui est plutôt l'acte d'un anti-bot .

**Comment by asyade** [comment]
Pas d'antian, a toi d en devlopper une ;)

**Comment by Spyrow** [comment]
Après vous avez peut être raison j'utilise plus ce bot mais un autre donc ils ont surement dév un anti bot sur celui que j'utilise

**Comment by iron-maiden74** [comment]
Alors du coup , depuis ce message que j'ai posté, je me suis fais ban 3 fois.
après analyse des logs, j'en déduis ceci : 
- ban 1 : 5 bot connecté, 1 bot combat qui abusait un peu (beaucoup trop rapide) -> ban avec un message de modérateur
- ban 2 : 4 bots connecté, que du récolte, et durant la nuit (après 2-3 nuit de botting), 2 des 4 bots sont  téléporté en prison par un modo, et apres quelques secondes, tous les bots sont ban.
-ban 3 : 1 seul bot connecté, en mode combat, et apres seulement quelques heures, ban instantané, sans message de modérateur, sans rien..

Du coup je pense que le problème vient de modérateur qui suspectent le bot, et apres observation, bannissent tout les comptes sur la meme IP.
La question est : pourquoi me suspecte il ? et comment faire en sorte de détecter un modérateur sur la map...

**Comment by zahiid** [comment]
les serveurs dofus touch sont surpeuplés et les gens n'ont surtout pas la flemme de reporter un bot ;) . Je te conseille de botter plus modérément .
